#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include "main.h"

#define BOARD_FW_NAME "TDPS_BoardTest"
#define BOARD_FW_VERSION "2026-05-26"
#define BOARD_DEBUG_UART_BAUD 115200U
#define BOARD_MOTOR_DEFAULT_MAX_DUTY 50
#define BOARD_MOTOR_DEFAULT_MAX_MS 10000U

#define BOARD_MOTOR_A_TIMER htim8
#define BOARD_MOTOR_A_CHANNEL TIM_CHANNEL_3
#define BOARD_MOTOR_B_TIMER htim10
#define BOARD_MOTOR_B_CHANNEL TIM_CHANNEL_1

#define BOARD_MOTOR_A_FORWARD_STATE GPIO_PIN_SET
#define BOARD_MOTOR_A_REVERSE_STATE GPIO_PIN_RESET
#define BOARD_MOTOR_B_FORWARD_STATE GPIO_PIN_SET
#define BOARD_MOTOR_B_REVERSE_STATE GPIO_PIN_RESET
#define BOARD_LORA_RST_IDLE_STATE GPIO_PIN_SET
#define BOARD_LORA_RST_ACTIVE_STATE GPIO_PIN_RESET

#endif
